# Generated by Django 5.2.7 on 2025-10-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('percent', models.FloatField()),
                ('year', models.IntegerField()),
                ('days', models.IntegerField()),
            ],
        ),
    ]
