# Generated by Django 5.2.7 on 2025-10-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarecord',
            name='position',
            field=models.IntegerField(),
        ),
    ]
